import Navber from '@/components/Shared/Navber/Navber'
import './globals.css'
import CursorAnimation from '@/components/Shared/CursorAnimation/CursorAnimation'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
     <Navber/>
     {/* <CursorAnimation/> */}
        {children}
        </body>
    </html>
  )
}
